remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: AWS Cloud Practitioner CheatSheet
description: AWS Cloud Practitioner CheatSheet
show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]